// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nullint.proto

package nullint

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NullInt ...
type NullInt struct {
	// Represents the actual Integer
	Int int64 `protobuf:"varint,1,opt,name=int,proto3" json:"int,omitempty"`
	// is set to true if the integer is null
	IsNotNull            bool     `protobuf:"varint,2,opt,name=is_not_null,json=isNotNull,proto3" json:"is_not_null,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullInt) Reset()         { *m = NullInt{} }
func (m *NullInt) String() string { return proto.CompactTextString(m) }
func (*NullInt) ProtoMessage()    {}
func (*NullInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_6833ff387ce205c8, []int{0}
}

func (m *NullInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullInt.Unmarshal(m, b)
}
func (m *NullInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullInt.Marshal(b, m, deterministic)
}
func (m *NullInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullInt.Merge(m, src)
}
func (m *NullInt) XXX_Size() int {
	return xxx_messageInfo_NullInt.Size(m)
}
func (m *NullInt) XXX_DiscardUnknown() {
	xxx_messageInfo_NullInt.DiscardUnknown(m)
}

var xxx_messageInfo_NullInt proto.InternalMessageInfo

func (m *NullInt) GetInt() int64 {
	if m != nil {
		return m.Int
	}
	return 0
}

func (m *NullInt) GetIsNotNull() bool {
	if m != nil {
		return m.IsNotNull
	}
	return false
}

func init() {
	proto.RegisterType((*NullInt)(nil), "roockie.protobuf.NullInt")
}

func init() { proto.RegisterFile("nullint.proto", fileDescriptor_6833ff387ce205c8) }

var fileDescriptor_6833ff387ce205c8 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2b, 0xcd, 0xc9,
	0xc9, 0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x28, 0xca, 0xcf, 0x4f, 0xce,
	0xce, 0x4c, 0x85, 0x70, 0x93, 0x4a, 0xd3, 0x94, 0xac, 0xb9, 0xd8, 0xfd, 0x4a, 0x73, 0x72, 0x3c,
	0xf3, 0x4a, 0x84, 0x04, 0xb8, 0x98, 0x33, 0xf3, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83,
	0x40, 0x4c, 0x21, 0x39, 0x2e, 0xee, 0xcc, 0xe2, 0xf8, 0xbc, 0xfc, 0x92, 0x78, 0x90, 0x31, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x9c, 0x99, 0xc5, 0x7e, 0xf9, 0x25, 0x20, 0x4d, 0x4e, 0x46,
	0x51, 0x06, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x50, 0xb3, 0x75,
	0xf3, 0x52, 0x93, 0x4a, 0x73, 0x12, 0xf5, 0x61, 0x56, 0xe8, 0x97, 0x54, 0x16, 0xa4, 0x16, 0xeb,
	0x43, 0x1d, 0x92, 0xc4, 0x06, 0x16, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x02, 0x73, 0x93,
	0xa4, 0x9a, 0x00, 0x00, 0x00,
}
