// Code generated by protoc-gen-go. DO NOT EDIT.
// source: duration.proto

package duration

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Duration ...
type Duration struct {
	// Signed nanoseconds of the span of time. Must be from -315,576,000,000,000
	// to +315,576,000,000,000 inclusive. Note: these bounds are computed from:
	// 1000 ms/sec * 60 sec/min * 60 min/hr * 24 hr/day * 365.25 days/year * 10000 years
	Nanos int64 `protobuf:"varint,1,opt,name=nanos,proto3" json:"nanos,omitempty"`
	// is set to true if the timestamp is null
	IsNotNull            bool     `protobuf:"varint,2,opt,name=is_not_null,json=isNotNull,proto3" json:"is_not_null,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Duration) Reset()         { *m = Duration{} }
func (m *Duration) String() string { return proto.CompactTextString(m) }
func (*Duration) ProtoMessage()    {}
func (*Duration) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c557e36239b70f1, []int{0}
}

func (m *Duration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Duration.Unmarshal(m, b)
}
func (m *Duration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Duration.Marshal(b, m, deterministic)
}
func (m *Duration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Duration.Merge(m, src)
}
func (m *Duration) XXX_Size() int {
	return xxx_messageInfo_Duration.Size(m)
}
func (m *Duration) XXX_DiscardUnknown() {
	xxx_messageInfo_Duration.DiscardUnknown(m)
}

var xxx_messageInfo_Duration proto.InternalMessageInfo

func (m *Duration) GetNanos() int64 {
	if m != nil {
		return m.Nanos
	}
	return 0
}

func (m *Duration) GetIsNotNull() bool {
	if m != nil {
		return m.IsNotNull
	}
	return false
}

func init() {
	proto.RegisterType((*Duration)(nil), "dkfbasel.protobuf.Duration")
}

func init() { proto.RegisterFile("duration.proto", fileDescriptor_0c557e36239b70f1) }

var fileDescriptor_0c557e36239b70f1 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x29, 0x2d, 0x4a,
	0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4c, 0xc9, 0x4e, 0x4b,
	0x4a, 0x2c, 0x4e, 0xcd, 0x81, 0xf0, 0x93, 0x4a, 0xd3, 0x94, 0x1c, 0xb8, 0x38, 0x5c, 0xa0, 0x8a,
	0x84, 0x44, 0xb8, 0x58, 0xf3, 0x12, 0xf3, 0xf2, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83,
	0x20, 0x1c, 0x21, 0x39, 0x2e, 0xee, 0xcc, 0xe2, 0xf8, 0xbc, 0xfc, 0x92, 0xf8, 0xbc, 0xd2, 0x9c,
	0x1c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0xce, 0xcc, 0x62, 0xbf, 0xfc, 0x12, 0xbf, 0xd2,
	0x9c, 0x1c, 0x27, 0xdd, 0x28, 0xed, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c,
	0x7d, 0x98, 0x0d, 0xfa, 0x30, 0x1b, 0xf4, 0x4b, 0x2a, 0x0b, 0x52, 0x8b, 0xf5, 0x61, 0x2e, 0x49,
	0x62, 0x03, 0x4b, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x71, 0xd8, 0xc3, 0x15, 0x9c, 0x00,
	0x00, 0x00,
}
