// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nullstring.proto

package nullstring

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// NullString ...
type NullString struct {
	// Represents the actual string
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// is set to true if the string is null
	IsNotNull            bool     `protobuf:"varint,2,opt,name=is_not_null,json=isNotNull,proto3" json:"is_not_null,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullString) Reset()         { *m = NullString{} }
func (m *NullString) String() string { return proto.CompactTextString(m) }
func (*NullString) ProtoMessage()    {}
func (*NullString) Descriptor() ([]byte, []int) {
	return fileDescriptor_eca726d7d5663138, []int{0}
}

func (m *NullString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullString.Unmarshal(m, b)
}
func (m *NullString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullString.Marshal(b, m, deterministic)
}
func (m *NullString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullString.Merge(m, src)
}
func (m *NullString) XXX_Size() int {
	return xxx_messageInfo_NullString.Size(m)
}
func (m *NullString) XXX_DiscardUnknown() {
	xxx_messageInfo_NullString.DiscardUnknown(m)
}

var xxx_messageInfo_NullString proto.InternalMessageInfo

func (m *NullString) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *NullString) GetIsNotNull() bool {
	if m != nil {
		return m.IsNotNull
	}
	return false
}

func init() {
	proto.RegisterType((*NullString)(nil), "roockie.protobuf.NullString")
}

func init() { proto.RegisterFile("nullstring.proto", fileDescriptor_eca726d7d5663138) }

var fileDescriptor_eca726d7d5663138 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x2b, 0xcd, 0xc9,
	0x29, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x28, 0xca,
	0xcf, 0x4f, 0xce, 0xce, 0x4c, 0x85, 0x70, 0x93, 0x4a, 0xd3, 0x94, 0x1c, 0xb8, 0xb8, 0xfc, 0x4a,
	0x73, 0x72, 0x82, 0xc1, 0xaa, 0x84, 0x84, 0xb8, 0x58, 0x4a, 0x52, 0x2b, 0x4a, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x39, 0x2e, 0xee, 0xcc, 0xe2, 0xf8, 0xbc, 0xfc, 0x92,
	0x78, 0x90, 0x71, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x9c, 0x99, 0xc5, 0x7e, 0xf9, 0x25,
	0x20, 0x9d, 0x4e, 0xa6, 0x51, 0xc6, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9,
	0xfa, 0x50, 0x0b, 0x74, 0xf3, 0x52, 0x93, 0x4a, 0x73, 0x12, 0xf5, 0x61, 0xf6, 0xe8, 0x97, 0x54,
	0x16, 0xa4, 0x16, 0xeb, 0x23, 0x1c, 0x94, 0xc4, 0x06, 0x96, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xd4, 0x0e, 0x95, 0xce, 0xa5, 0x00, 0x00, 0x00,
}
