// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timestamp.proto

package timestamp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Timestamp ...
type Timestamp struct {
	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z
	Milliseconds int64 `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	// is set to true if the timestamp is null
	IsNotNull            bool     `protobuf:"varint,2,opt,name=is_not_null,json=isNotNull,proto3" json:"is_not_null,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_edac929d8ae1e24f, []int{0}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetMilliseconds() int64 {
	if m != nil {
		return m.Milliseconds
	}
	return 0
}

func (m *Timestamp) GetIsNotNull() bool {
	if m != nil {
		return m.IsNotNull
	}
	return false
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "roockie.protobuf.Timestamp")
}

func init() { proto.RegisterFile("timestamp.proto", fileDescriptor_edac929d8ae1e24f) }

var fileDescriptor_edac929d8ae1e24f = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xc9, 0xcc, 0x4d,
	0x2d, 0x2e, 0x49, 0xcc, 0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x28, 0xca, 0xcf,
	0x4f, 0xce, 0xce, 0x4c, 0x85, 0x70, 0x93, 0x4a, 0xd3, 0x94, 0xfc, 0xb9, 0x38, 0x43, 0x60, 0x8a,
	0x84, 0x94, 0xb8, 0x78, 0x72, 0x33, 0x73, 0x72, 0x32, 0x8b, 0x53, 0x93, 0xf3, 0xf3, 0x52, 0x8a,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x50, 0xc4, 0x84, 0xe4, 0xb8, 0xb8, 0x33, 0x8b, 0xe3,
	0xf3, 0xf2, 0x4b, 0xe2, 0xf3, 0x4a, 0x73, 0x72, 0x24, 0x98, 0x14, 0x18, 0x35, 0x38, 0x82, 0x38,
	0x33, 0x8b, 0xfd, 0xf2, 0x4b, 0xfc, 0x4a, 0x73, 0x72, 0x9c, 0x4c, 0xa2, 0x8c, 0xd2, 0x33, 0x4b,
	0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0xa1, 0xf6, 0xe9, 0xe6, 0xa5, 0x26, 0x95, 0xe6,
	0x24, 0xea, 0xc3, 0xac, 0xd5, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x87, 0x3b, 0x2f, 0x89, 0x0d,
	0x2c, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x72, 0xe5, 0x53, 0x80, 0xb2, 0x00, 0x00, 0x00,
}
